on:
  - workflow_call
  - workflow_dispatch
  
name: Push Files to Azure Storage
run-name: Build & Push Docker Image ${{ vars.GITHUB_RUN_ID }} - ${{ vars.GITHUB_SHA }}

jobs:
  push-files:
    name: Push extra files to Azure to override the defaults
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the latest version of the repo
      uses: actions/checkout@v3
    
    - name: Login to Auzre for files upload
      uses: azure/login@v1
      with:     
        creds: '{"clientId":"${{ secrets.AZURE_DEPLOYMENT_GUID }}","clientSecret":"${{ secrets.AZURE_DEPLOYMENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

    - name: Upload wp-content/themes
      # You may pin to the exact commit or the version.
      uses: rnakamine/azure-files-upload@v1.0.0
      with:
        # The connection string for the storage account.
        connection_string: ${{ secrets.AZURE_FILES_CONNECTION_STRING }}
        # The directory to upload files from.
        source: ./files/httpdocs/wp-content/themes
        # The destination of the upload operation.
        destination: wp-content-themes
        
    - name: Upload wp-content/plugins
      # You may pin to the exact commit or the version.
      uses: rnakamine/azure-files-upload@v1.0.0
      with:
        # The connection string for the storage account.
        connection_string: ${{ secrets.AZURE_FILES_CONNECTION_STRING }}
        # The directory to upload files from.
        source: ./files/httpdocs/wp-content/plugins
        # The destination of the upload operation.
        destination: wp-content-plugins
      
    - name: Upload wp-content/uploads
      # You may pin to the exact commit or the version.
      uses: rnakamine/azure-files-upload@v1.0.0
      with:
        # The connection string for the storage account.
        connection_string: ${{ secrets.AZURE_FILES_CONNECTION_STRING }}
        # The directory to upload files from.
        source: ./files/httpdocs/wp-content/uploads
        # The destination of the upload operation.
        destination: wp-content-uploads
      
