on:
  - workflow_call
  - workflow_dispatch

name: Build & push image to ACR
run-name: Build & Push Image to ACR ${{ github.head_ref }} - ${{ github.run_id }} - ${{ github.sha }}

jobs:
  build:
    name: Build and push the image to Azure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the latest version of the repo
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: restoringpride.azurecr.io
          # Username used to log against the Docker registry
          username: ${{ secrets.AZURE_DEPLOYMENT_GUID }} # optional
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.AZURE_DEPLOYMENT_SECRET }} # optional

      - name: Build the Docker image
        run: docker build . -t restoringpride.azurecr.io/restoringpride:${{ github.sha }} -t restoringpride.azurecr.io/restoringpride:latest

      - name: Push the docker image to Azure
        run: |
          docker push restoringpride.azurecr.io/restoringpride:${{ github.sha }} 
          docker push restoringpride.azurecr.io/restoringpride:latest
