name: Build & deploy the whole shebang
run-name: Build & deploy the whole shebang ${{ github.head_ref }}

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  actions: write
  id-token: write
  contents: read

concurrency:
  group: Build and push the Docker image to Azure
  cancel-in-progress: true

jobs:
  nove-files-to-their-proper-places:
    runs-on: ubuntu-latest
    steps:
      - run: mv docker-compose-production.yml docker-compose-production.yml \
         mv Dockerfile.produdcrion Dockerfile \ 
         echo "LABEL=${{ github.sha }}" >> .env
      - name: Cache the modifid output
        uses: actions/cache@v2.1.8
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: . 
          # An explicit key for restoring and saving the cache
          key: resroringpride
          # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
          restore-keys: restoringpride
     

  build-docker-image:
    needs: nove-files-to-their-proper-places
    name: Build & deploy the Docker image to ACR
    uses: Restoring-Pride/RestoringPride.org/.github/workflows/build-and-push-docker-image-to-azure.yml@main
    secrets: inherit

  deploy-to-web-app:
    name: Deploy to the Web app
    uses: Restoring-Pride/RestoringPride.org/.github/workflows/deploy-the-image-to-the-web-app.yml@main
    needs: build-docker-image
    secrets: inherit

  done:
    runs-on: ubuntu-latest
    needs: deploy-to-web-app

    steps:
      - name: Say I'm done!
        run: echo "I'm fucking DONE, BITCHES!!!"
