name: Build & deploy the whole shebang
run-name: Build & deploy the whole shebang ${{ github.head_ref }}

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  actions: write
  id-token: write
  contents: read

concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: true

jobs:
  nove-and-populate-files-to-their-proper-places:
    name: Move & populate the file to their proper places
    uses: Restoring-Pride/RestoringPride.org/.github/workflows/pull-the-repo-and-deploy-directly-within-ACR.yml@main
    secrets: inherit

  build-docker-image:
    needs: nove-and-populate-files-to-their-proper-places
    name: Build & deploy the Docker image to ACR
    uses: Restoring-Pride/RestoringPride.org/.github/workflows/pull-the-repo-and-deploy-directly-within-ACR.yml@main
    secrets: inherit

  deploy-to-web-app:
    name: Deploy to the Web app
    uses: Restoring-Pride/RestoringPride.org/.github/workflows/deploy-the-image-to-the-web-app.yml@main
    needs: build-docker-image
    secrets: inherit

  done:
    runs-on: ubuntu-latest
    needs: deploy-to-web-app

    steps:
      - name: Say I'm done!
        run: echo "I'm fucking DONE, BITCHES!!!"
