name: Build & deploy the whole shebang

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: 
  actions: write
  id-token: write
  contents: read

concurrency: 
  group: Build and push the Docker image to Azure
  cancel-in-progress: true

jobs:

  call-build-docker-image:
    uses: Restoring-Pride/RestoringPride.org/.github/workflows/build-and-push-docker-image-to-azure.yml@main
    name: Build & deploy the Docker image to ACR
    
  deploy-files:
    uses: Restoring-Pride/RestoringPride.org/.github/workflows/push_files_to_azure_storage.yml@main
    name: Push files to Azure storage
    needs: call-build-docker-image
    
  deploy-to-web-app:
    uses: Restoring-Pride/RestoringPride.org/.github/workflows/deploy-the-image-to-the-web-app.yml@main
    needs: deploy-files
    
  done:
    runs-on: ubuntu-latest
    needs: deploy-to-web-app
    
    steps:
      - name: Say I'm done!
        run: echo "I'm fucking DONE, BITCHES!!!"
    
    
  
