name: Build and push the Docker image to Azure

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build and push the image to Azure
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the latest version of the repo
      uses: actions/checkout@v3
      
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: restoringpride.azurecr.io
        # Username used to log against the Docker registry
        username:  ${{ secrets.AZURE_DEPLOYMENT_GUID }}  # optional
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.AZURE_DEPLOYMENT_SECRET }} # optional
  
    - name: Build the Docker image
      run: docker build --file ./files/httpdocs/Dockerfile -t restoringpride.azurecr.io/restoringpride:${{ github.sha }}-t restoringpride.azurecr.io/restoringpride:latest
      
    - name: Push the docker image to Azure
      run: |
        docker push restoringpride.azurecr.io/restoringpride:${{ github.sha }} 
        docker push restoringpride.azurecr.io/restoringpride:latest
    
    - name: Deploy the image to the Web app
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'restoringpride-wp'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'restoringpride.azurecr.io/restoringpride:latest'

  push-files:
    name: Push extra files to Azure to override the defaults
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout the latest version of the repo
      uses: actions/checkout@v3
    
    - name: Login to Auzre for files upload
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.AZURE_DEPLOYMENT_USERNAME }}", "clientSecret": "${{ secrets.AZURE_DEPLOYMENT_SECRET }}", "tenantId":"${{ secrets.AZURE_TENANT_ID }}", "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}"}'

    - name: Upload wp-content/themes
      # You may pin to the exact commit or the version.
      # uses: rnakamine/azure-files-upload@5c1081adbe0d65b9c0a8be234f0e17ae93c8b741
      uses: rnakamine/azure-files-upload@v1.0.0
      with:
        # The connection string for the storage account.
        connection_string: ${{ secrets.AZURE_FILES_CONNECTION_STRING }}
        # The directory to upload files from.
        source: ./files/httpdocs/wp-content/themes
        # The destination of the upload operation.
        destination: restoringpride/wp-content/themes
        
    - name: Upload wp-content/plugins
      # You may pin to the exact commit or the version.
      # uses: rnakamine/azure-files-upload@5c1081adbe0d65b9c0a8be234f0e17ae93c8b741
      uses: rnakamine/azure-files-upload@v1.0.0
      with:
        # The connection string for the storage account.
        connection_string: ${{ secrets.AZURE_FILES_CONNECTION_STRING }}
        # The directory to upload files from.
        source: ./files/httpdocs/wp-content/plugins
        # The destination of the upload operation.
        destination: restoringpride/wp-content/plugins
        
    - name: Upload wp-config.php
      # You may pin to the exact commit or the version.
      # uses: rnakamine/azure-files-upload@5c1081adbe0d65b9c0a8be234f0e17ae93c8b741
      uses: rnakamine/azure-files-upload@v1.0.0
      with:
        # The connection string for the storage account.
        connection_string: ${{ secrets.AZURE_FILES_CONNECTION_STRING }}
        # The directory to upload files from.
        source: ./files/httpdocs/wp-config.php
        # The destination of the upload operation.
        destination: restoringpride/wp-config.php
  
    
      
