on:
  - workflow_call
  - workflow_dispatch

name: Deploy the image to the Web app
run-name: Deploy the image to the Web app ${{ github.head_ref }} - ${{ github.run_id }} - ${{ github.sha }}

jobs:
  deploy-to-web-app:
    runs-on: ubuntu-latest
    name: Deploy the image to the Web app
    
    steps:
      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          # ClientId of the Azure Service principal created.
          client-id: ${{secrets.AZURE_DEPLOYMENT_GUID }} # optional
          # TenantId of the Azure Service principal created.
          tenant-id: ${{secrets.AZURE_TENANT_ID }}# optional
          # Azure subscriptionId
          subscription-id: ${{secrets.AZURE_SUBSCRPTION_ID }}# optional
          # Set this value to true to enable Azure PowerShell Login in addition to Az CLI login
#           enable-AzPSSession: # optional
          # Name of the environment. Supported values are azurecloud, azurestack, azureusgovernment, azurechinacloud, azuregermancloud. Default being azurecloud
#           environment: # optional, default is azurecloud
          # Set this value to true to enable support for accessing tenants without subscriptions
#           allow-no-subscriptions: # optional
          # Provide audience field for access-token. Default value is api://AzureADTokenExchange
#           audience: # optional, default is api://AzureADTokenExchange
          
      - name: Setup Docker /home/docker-compose.yml
        run: az webapp config container set \
            --docker-custom-image-name "restoringpride"
            --docker-registry-server-url https://restoringpride.azurecr.io
            --docker-registry-server-user ${{ secrets.AZURE_DEPLOYMENT_GUID }}
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP_NAME }} \
            --name ${{ secrets.AZURE_APP_NAME }} \
            --multicontainer-config-type compose
