on:
  - workflow_call
  - workflow_dispatch
  
name: Deploy the image to the Web app
run-name: Deploy the image to the Web app ${{ vars.GITHUB_RUN_ID }} - ${{ vars.GITHUB_SHA }}

jobs:
  deploy-to-web-app:
    runs-on: ubuntu-latest
    name: Deploy the image to the Web app
    steps:
    
    - name: Deploy the image to the Web app
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'restoringpridedotorg'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'restoringpride.azurecr.io/restoringpride:latest'
        
