on:
  - workflow_call
  - workflow_dispatch

name: Deploy the image to the Web app
run-name: Deploy the image to the Web app ${{ github.head_ref }} - ${{ github.run_id }} - ${{ github.sha }}

jobs:
  deploy-to-web-app:
    runs-on: ubuntu-latest
    name: Deploy the image to the Web app
    
    steps:
      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: '{"clientId":"${{ secrets.AZURE_DEPLOYMENT_GUID }}","clientSecret":"${{ secrets.AZURE_DEPLOYMENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
          
      - name: Setup Docker /home/docker-compose.yml
        run: az webapp config container set \
            --docker-custom-image-name "restoringpride"
            --docker-registry-server-url https://restoringpride.azurecr.io
            --docker-registry-server-user ${{ secrets.AZURE_DEPLOYMENT_GUID }}
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP_NAME }} \
            --name ${{ secrets.AZURE_APP_NAME }} \
            --multicontainer-config-type compose
