on:
  - workflow_call
  - workflow_dispatch

name: Build & push image to ACR
run-name: Build & Push Image to ACR ${{ github.head_ref }} - ${{ github.run_id }} - ${{ github.sha }}

permissions:
  actions: write
  id-token: write
  contents: read

jobs:
  build-within-azr:
    name: Build and push the image to Azure
    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      run: |
          docker build --pull --rm  \
          -f "./Dockerfile"  \
          -t restoringpride:${{ github.sha }} \
          -t restoringpride:latest \
          "." 
          
    - name: Azure Login
      run: az login --service-principal \
            --username "${{ secrets.AZURE_SERVICE_PRINCIPAL_URI }}" \
            --password "${{ secrets.AZURE_SERVICE_PRINCIPAL_SECRET }}" \
            --tenant "${{ secrets.AZURE_TENANT_DOMAIN }}"

    - name: Build the container directly in the registry
      run: docker login restoringpride.azurecr.io -u  "${{ secrets.AZURE_SERVICE_PRINCIPAL_URI }}"  -p "${{ secrets.AZURE_SERVICE_PRINCIPAL_SECRET }}"
      
