on:
  - workflow_call
  - workflow_dispatch

name: Build & push image to ACR
run-name: Build & Push Image to ACR (${{ github.run_id }})

permissions:
  actions: write
  id-token: write
  contents: read

jobs:
  build-within-azr:
    name: Build and push the image to Azure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the deployment branch
        uses: actions/checkout@3.4.0
        with:
          ref: deployment
    
      - name: Build the Docker image
        run: |
            docker build --pull --rm  \
            -f "./Dockerfile"  \
            -t restoringpride:${{ github.sha }} \
            -t restoringpride:latest \
            "." 
          
      - name: Azure Login
        run: az login --service-principal \
              --username "${{ secrets.AZURE_SERVICE_PRINCIPAL_URI }}" \
              --password "${{ secrets.AZURE_SERVICE_PRINCIPAL_SECRET }}" \
              --tenant "${{ secrets.AZURE_TENANT_DOMAIN }}"
